services:
  http_server:
    image: code_runner-http_server-dev:latest
    build:
      context: http_server
      dockerfile: Dockerfile.dev
    environment:
      BUILD_PATH: ${HTTPSERVER_BUILD_PATH}
      ARGS: ${HTTPSERVER_ARGS}
    volumes:
      - ./http_server:/app
    ports:
      - "8080:8080"
      - "2112:2112"
      - "43777:43777"

  consumer:
    image: code_runner-consumer-dev:latest
    build:
      context: consumer
      dockerfile: Dockerfile.dev
    environment:
      BUILD_PATH: ${CONSUMER_BUILD_PATH}
      ARGS: ${CONSUMER_ARGS}
    volumes:
      - ./consumer:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "43778:43777"
  postgres:
    ports:
      - "5432:5432"
  broker:
    ports:
      - "5672:5672"
      - "15672:15672"
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - http_server
    networks:
      - code_runner_network

  grafana:
    image: grafana/grafana:latest
    ports: 
      - 3000:3000
    networks:
      - code_runner_network
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: