services:
  http_server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Use !override to discard the postgres dependency from the base file
    depends_on: !override
      broker: 
        condition: service_healthy
      redis: 
        condition: service_healthy
    environment:
      - POSTGRES_HOST=host.docker.internal

  consumer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Use !override here as well
    depends_on: !override
      broker: 
        condition: service_healthy
    environment:
      - POSTGRES_HOST=host.docker.internal

  postgres:
    profiles:
      - donotrun
