networks:
  code_runner_network:
    external: true

services:
  app_test:
    build:
      context: tests
      dockerfile: Dockerfile
    environment:
      - BASE_URL
    depends_on:
      http_server:
        condition: service_healthy
    networks:
      - code_runner_network

      
