networks:
  code_runner_network:
    external: true

services:
  http_server:
    build:
      context: .
      dockerfile: http_server/Dockerfile
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - REDIS_PASSWORD
      - REDIS_ADDRESSES
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s 
      timeout: 10s   
      retries: 3     
      start_period: 10s
    depends_on:
      broker: 
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - code_runner_network
  
  broker:
    image: "rabbitmq:3-management"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - code_runner_network

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    depends_on:
      broker: 
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - code_runner_network


  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d code_runner"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - code_runner_network
  




  
volumes:
  postgres_data:
  redis_data:


