FROM golang:1.25.0

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY go.mod go.sum ./

RUN go mod download

EXPOSE 43777

ENTRYPOINT ["sh", "-c", "go build -gcflags='all=-N -l' -o /tmp/main ${BUILD_PATH} && dlv exec /tmp/main --headless=true --listen=:43777 --api-version=2 --accept-multiclient --continue -- ${ARGS}"]
