- name: Ensure redis cluster user exists
  ansible.builtin.user:
    name: "{{ redis_cluster_user }}"
    system: yes
    shell: /usr/sbin/nologin
  become: true

- name: Ensure /opt directory with correct ownership
  ansible.builtin.file:
    path: "{{ redis_cluster_repo_path }}"
    state: directory
    owner: "{{ redis_cluster_user }}"
    group: "{{ redis_cluster_user }}"
    mode: '0755'
  become: true

- name: Clone Redis Cluster repository
  ansible.builtin.git:
    repo: "{{ redis_cluster_repo_github }}"
    dest: "{{ redis_cluster_repo_path }}"
    version: validation
  become: true
  become_user: "{{ redis_cluster_user }}"
  notify: restart redis_cluster

- name: Copy .env file to the server
  template:
    src: "{{ redis_cluster_repo_env_file }}.j2"
    dest: "{{ redis_cluster_repo_env_file_path }}"
    mode: '0600'
  become: true
  become_user: "{{ redis_cluster_user }}"

- name: Create systemd unit file
  ansible.builtin.template:
    src: "{{ redis_cluster_service_name }}.service.j2"
    dest: "/etc/systemd/system/{{ redis_cluster_service_name }}.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart redis_cluster

- name: Ensure the service is started and enabled on boot
  ansible.builtin.systemd_service:
    name: "{{ redis_cluster_service_name }}"
    state: started
    enabled: true
    daemon_reload: true