apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consumer-job-manager
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: consumer
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
