---
- name: Install repo prerequisites
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo_url }}"
    state: present
    filename: docker

- name: Install Docker components
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes