- name: Install PostgreSQL packages
  ansible.builtin.include_tasks: install.yml

- name: Configure PostgreSQL settings
  ansible.builtin.include_tasks: config.yml

- name: Setup application users and databases
  ansible.builtin.include_tasks: database.yml

- name: Setup backup and cloud sync logic
  ansible.builtin.include_tasks: backup.yml

- name: Ensure the service is started and enabled on boot
  ansible.builtin.systemd_service:
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: true

- name: Setup postgres exporter
  ansible.builtin.include_tasks: exporter.yml