prometheus:
  version: "3.10.0"
  user: "prometheus"
  dir: "/etc/prometheus"
  data_dir: "/var/lib/prometheus"
  targets:
    self: '{{ prometheus_metrics_address | default(["localhost:9090"]) }}'
    code_runner: '{{ code_runner_metrics_address | default(["localhost:2112"]) }}'
    node_exporter: '{{ node_exporter_metrics_address | default(["localhost:9100"]) }}'
    pushgateway: "localhost:9091"
  service_name: "prometheus"