basePath: /
definitions:
  dto.Error:
    properties:
      error:
        type: string
    type: object
  dto.GetTaskResultHandlerResponse:
    properties:
      result:
        type: string
    type: object
  dto.GetTaskStatusHandlerResponse:
    properties:
      status:
        type: string
    type: object
  dto.PostTaskHandlerRequest:
    properties:
      task_code:
        type: string
      task_translator:
        type: string
    type: object
  dto.PostTaskHandlerResponse:
    properties:
      id:
        type: string
    type: object
  dto.PostUserLoginHandlerRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  dto.PostUserLoginHandlerResponse:
    properties:
      token:
        type: string
    type: object
  dto.PostUserRegisterHandlerRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a code runner.
  title: code_processor/http_server
  version: "1.0"
paths:
  /task:
    post:
      consumes:
      - application/json
      description: Create a new task with the specified key and value
      parameters:
      - description: task code and translator
        in: body
        name: translation_data
        required: true
        schema:
          $ref: '#/definitions/dto.PostTaskHandlerRequest'
      - description: Bearer token for authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.PostTaskHandlerResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Create an task
      tags:
      - task
  /task/result/{id}:
    get:
      consumes:
      - application/json
      description: Get a task result by its id
      parameters:
      - description: Id of the task
        in: path
        name: id
        required: true
        type: string
      - description: Bearer token for authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetTaskResultHandlerResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "404":
          description: Task not found
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Get a task result
      tags:
      - task
  /task/status/{id}:
    get:
      consumes:
      - application/json
      description: Get a task status by its id
      parameters:
      - description: Id of the task
        in: path
        name: id
        required: true
        type: string
      - description: Bearer token for authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetTaskStatusHandlerResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "404":
          description: Task not found
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Get a task status
      tags:
      - task
  /user/login:
    post:
      consumes:
      - application/json
      description: Logins new user and creates new session for him
      parameters:
      - description: user login and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.PostUserLoginHandlerRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PostUserLoginHandlerResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.Error'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Login a user
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: Registers new user and adds them to data base
      parameters:
      - description: user login and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.PostUserRegisterHandlerRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/dto.Error'
        "409":
          description: Key already exists
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Register a user
      tags:
      - user
swagger: "2.0"
