redis_cluster_service_name: redis_cluster

redis_cluster_description: "Docker Compose redis cluster"
redis_cluster_start_limit_burst: 5
redis_cluster_start_limit_interval_sec: "100s"
redis_cluster_start_command: "docker compose -f compose.yml up -d"
redis_cluster_stop_command: "docker compose -f compose.yml down"
redis_cluster_restart_sec: "10s"

redis_cluster_repo_path: /opt/redis_cluster
redis_cluster_user: redis_cluster

redis_cluster_env_file: ".env"
redis_cluster_env_file_path: "{{ redis_cluster_repo_path }}/{{ redis_cluster_env_file }}"

redis_cluster_compose_file: "compose.yml"
redis_cluster_compose_file_path: "{{ redis_cluster_repo_path }}/{{ redis_cluster_compose_file }}"

redis_cluster_config_file: "redis.conf"
redis_cluster_config_file_path: "{{ redis_cluster_repo_path }}/{{ redis_cluster_config_file }}"

