redis_cluster_service_name: redis_cluster

redis_cluster_description: "Docker Compose redis cluster"
redis_cluster_start_limit_burst: 5
redis_cluster_start_limit_interval_sec: "100s"
redis_cluster_start_command: "cluster-up"
redis_cluster_stop_command: "cluster-down"
redis_cluster_restart_sec: "10s"

redis_cluster_repo_github: https://github.com/kirmala/code_runner
redis_cluster_repo_path: /opt/code_runner
redis_cluster_repo_env_file: ".env"
redis_cluster_repo_env_file_path: "{{ redis_cluster_repo_path }}/{{ redis_cluster_repo_env_file }}"

make_path: "/usr/bin/make"