redis_cluster_path: "/opt/redis_cluster"

redis_cluster:
  service_name: "redis_cluster"
  description: "Docker Compose redis cluster"
  user: "redis_cluster"
  repo_path: "{{ redis_cluster_path }}"
  network: "{{ docker_network_name | default('code_runner_network')}}"
  
  limits:
    burst: 5
    interval_sec: "100s"
    restart_sec: "10s"

  commands:
    start: "docker compose -f compose.yml up -d"
    stop: "docker compose -f compose.yml down"

  files:
    env: "{{ redis_cluster_path }}/.env"
    compose: "{{ redis_cluster_path }}/compose.yml"
    config: "{{ redis_cluster_path }}/redis.conf"
  
  image: "redis:7.2-alpine"
  nodes:
    - { name: "redis-node-1", vol: "redis_data_1", port: 6379, bus_port: 16379 }
    - { name: "redis-node-2", vol: "redis_data_2", port: 6380, bus_port: 16380 }
    - { name: "redis-node-3", vol: "redis_data_3", port: 6381, bus_port: 16381 }
    - { name: "redis-node-4", vol: "redis_data_4", port: 6382, bus_port: 16382 }
    - { name: "redis-node-5", vol: "redis_data_5", port: 6383, bus_port: 16383 }
    - { name: "redis-node-6", vol: "redis_data_6", port: 6384, bus_port: 16384 }
    
