- name: Apply common configuration to all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Setup PostgreSQL Database
  hosts: database
  become: true
  roles:
    - postgres

- name: Install Container Engine
  hosts: 
    - cache
    - app
  roles:
    - docker
  become: true


- name: Setup Redis Cluster
  hosts: cache
  roles:
    - redis_cluster
  become: true

- name: Setup Code Runner
  hosts: app
  roles:
    - code_runner
  become: true

- name: Setup node exporter
  hosts: node_exporters
  roles:
    - node_exporter
  become: true
  

- name: Setup Prometheus
  hosts: prometheus
  roles:
    - prometheus
  become: true