- name: Apply common configuration to all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Setup PostgreSQL Database
  hosts: database
  become: true
  roles:
    - postgres

- name: Install Container Engine
  hosts: 
    - cache
    - app
  roles:
    - docker
