name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push http_server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./http_server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/code_runner-http_server:latest

      - name: Build and push consumer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./consumer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/code_runner-consumer:latest

      - name: Build and push sandbox
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./consumer/service/docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/code_runner-sandbox:latest

      - name: Build and push migrations
        uses: docker/build-push-action@v5
        with:
          context: ./http_server/repository/postgres
          file: ./http_server/repository/postgres/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/code_runner-migrations:latest

  integration_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Make
        run: sudo apt-get install make

      - name: Create .env file from template
        run: envsubst < .env.example > .env
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      
      - name: Run tests
        run: |
          mkdir -p integration_logs
          make test-up | tee integration_logs/app_test.log
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-logs
          path: integration_logs/
          
      - name: Cleanup
        if: always()
        run: make test-down

  # deploy:g
  #   runs-on: ubuntu-latest
  #   needs: integration_tests
  #   if: github.ref == 'refs/heads/main'
  #   environment: production
  #   steps:
  #     - name: Checkout code
  #       uses: [actions/checkout@v4](https://github.com)
        
  #     - name: Deploy
  #       run: |
  #         docker compose pull
  #         docker compose up -d
