name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose filter results as job outputs
      http_server: ${{ steps.filter.outputs.http_server }}
      consumer: ${{ steps.filter.outputs.consumer }}
      sandbox: ${{ steps.filter.outputs.sandbox }}
      migrations: ${{ steps.filter.outputs.migrations }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            http_server: ['http_server/**']
            consumer: ['consumer/**', '!consumer/service/docker/**']
            sandbox: ['consumer/service/docker/**']
            migrations: ['http_server/repository/postgres/**']

  build:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: http_server
            context: .
            file: ./http_server/Dockerfile
            tag: code_runner-http_server
          - service: consumer
            context: .
            file: ./consumer/Dockerfile
            tag: code_runner-consumer
          - service: sandbox
            context: .
            file: ./consumer/service/docker/Dockerfile
            tag: code_runner-sandbox
          - service: migrations
            context: ./http_server/repository/postgres
            file: ./http_server/repository/postgres/Dockerfile
            tag: code_runner-migrations
    
    # ONLY run this specific matrix job if changes were detected for this service
    if: needs.changes.outputs[matrix.service] == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}:latest
          # Layer caching makes the "push" faster because unchanged layers aren't re-uploaded
          cache-from: type=gha,scope=${{ matrix.service }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service }}


  integration_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Make
        run: sudo apt-get install make

      - name: Create .env file from template
        run: envsubst < .env.example > .env
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      
      - name: Run tests
        run: |
          mkdir -p integration_logs
          make test-up | tee integration_logs/app_test.log
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-logs
          path: integration_logs/
          
      - name: Cleanup
        if: always()
        run: make test-down

  deploy:
    runs-on: ubuntu-latest
    needs: integration_tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/site.yml
          inventory: ansible/inventory.ini
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
